import type { CaseDefinition } from '@/domain/case/caseSchema';

const always = { type: 'always' } as const;

export const blackBoxCase: CaseDefinition = {
  id: 'case-black-box',
  schemaVersion: 1,
  titleKey: 'cases.blackbox.title',
  summaryKey: 'cases.blackbox.summary',
  briefingKey: 'cases.blackbox.briefing',
  difficulty: 'hard',
  estimatedMinutes: 20,
  evidence: [
    {
      id: 'build-release',
      type: 'system_log',
      titleKey: 'cases.blackbox.evidence.build.title',
      descriptionKey: 'cases.blackbox.evidence.build.description',
      content: {
        kind: 'timeline_item',
        time: '02:00',
        bodyKey: 'cases.blackbox.evidence.build.body',
      },
      unlockCondition: always,
      tags: ['software', 'timeline'],
    },
    {
      id: 'drone-test',
      type: 'sensor_record',
      titleKey: 'cases.blackbox.evidence.drone.title',
      descriptionKey: 'cases.blackbox.evidence.drone.description',
      content: {
        kind: 'timeline_item',
        time: '02:13',
        bodyKey: 'cases.blackbox.evidence.drone.body',
      },
      unlockCondition: always,
      tags: ['drone', 'timeline'],
    },
    {
      id: 'route-test',
      type: 'location_record',
      titleKey: 'cases.blackbox.evidence.route.title',
      descriptionKey: 'cases.blackbox.evidence.route.description',
      content: {
        kind: 'timeline_item',
        time: '02:21',
        bodyKey: 'cases.blackbox.evidence.route.body',
      },
      unlockCondition: always,
      tags: ['route', 'timeline'],
    },
    {
      id: 'station-test',
      type: 'system_log',
      titleKey: 'cases.blackbox.evidence.station.title',
      descriptionKey: 'cases.blackbox.evidence.station.description',
      content: {
        kind: 'timeline_item',
        time: '02:34',
        bodyKey: 'cases.blackbox.evidence.station.body',
      },
      unlockCondition: always,
      tags: ['station', 'timeline'],
    },
    {
      id: 'hotel-test',
      type: 'system_log',
      titleKey: 'cases.blackbox.evidence.hotel.title',
      descriptionKey: 'cases.blackbox.evidence.hotel.description',
      content: {
        kind: 'timeline_item',
        time: '02:47',
        bodyKey: 'cases.blackbox.evidence.hotel.body',
      },
      unlockCondition: { type: 'puzzle_solved', puzzleId: 'blackbox-logs' },
      tags: ['hotel', 'timeline'],
    },
    {
      id: 'operator-note',
      type: 'statement',
      titleKey: 'cases.blackbox.evidence.note.title',
      descriptionKey: 'cases.blackbox.evidence.note.description',
      content: { kind: 'text', bodyKey: 'cases.blackbox.evidence.note.body' },
      unlockCondition: always,
      tags: ['statement'],
    },
  ],
  puzzles: [
    {
      id: 'blackbox-timeline',
      type: 'timeline',
      titleKey: 'cases.blackbox.timeline.title',
      instructionsKey: 'cases.blackbox.timeline.instructions',
      itemIds: ['hotel-test', 'route-test', 'build-release', 'station-test', 'drone-test'],
      correctOrder: ['build-release', 'drone-test', 'route-test', 'station-test', 'hotel-test'],
      unlockCondition: always,
      hints: [
        { id: 'bb-time-h1', level: 1, textKey: 'cases.blackbox.timeline.hint1' },
        {
          id: 'bb-time-h2',
          level: 2,
          textKey: 'cases.blackbox.timeline.hint2',
          highlightTargetId: 'build-release',
        },
        {
          id: 'bb-time-h3',
          level: 3,
          textKey: 'cases.blackbox.timeline.hint3',
          highlightTargetId: 'hotel-test',
        },
      ],
    },
    {
      id: 'blackbox-logs',
      type: 'log_analyzer',
      titleKey: 'cases.blackbox.logs.title',
      instructionsKey: 'cases.blackbox.logs.instructions',
      rows: [
        {
          id: 'bb-l1',
          time: '02:00',
          source: 'BUILD',
          level: 'info',
          device: 'CI-4',
          messageKey: 'cases.blackbox.logs.row1',
        },
        {
          id: 'bb-l2',
          time: '02:01',
          source: 'SIGN',
          level: 'warning',
          device: 'CI-4',
          messageKey: 'cases.blackbox.logs.row2',
        },
        {
          id: 'bb-l3',
          time: '02:13',
          source: 'DRONE',
          level: 'warning',
          device: 'D-17',
          messageKey: 'cases.blackbox.logs.row3',
        },
        {
          id: 'bb-l4',
          time: '02:21',
          source: 'ROUTE',
          level: 'warning',
          device: 'Cargo-04',
          messageKey: 'cases.blackbox.logs.row4',
        },
        {
          id: 'bb-l5',
          time: '02:34',
          source: 'RELAY',
          level: 'warning',
          device: 'R-2',
          messageKey: 'cases.blackbox.logs.row5',
        },
        {
          id: 'bb-l6',
          time: '02:47',
          source: 'TOKEN',
          level: 'warning',
          device: 'Hotel',
          messageKey: 'cases.blackbox.logs.row6',
        },
        {
          id: 'bb-l7',
          time: '03:00',
          source: 'BACKUP',
          level: 'info',
          device: 'Vault',
          messageKey: 'cases.blackbox.logs.row7',
        },
      ],
      requiredRowIds: ['bb-l2', 'bb-l3', 'bb-l4', 'bb-l5', 'bb-l6'],
      allowedMistakes: 0,
      unlockCondition: { type: 'puzzle_solved', puzzleId: 'blackbox-timeline' },
      hints: [
        { id: 'bb-log-h1', level: 1, textKey: 'cases.blackbox.logs.hint1' },
        {
          id: 'bb-log-h2',
          level: 2,
          textKey: 'cases.blackbox.logs.hint2',
          highlightTargetId: 'bb-l2',
        },
        {
          id: 'bb-log-h3',
          level: 3,
          textKey: 'cases.blackbox.logs.hint3',
          highlightTargetId: 'bb-l6',
        },
      ],
    },
    {
      id: 'blackbox-contradiction',
      type: 'contradiction',
      titleKey: 'cases.blackbox.contradiction.title',
      instructionsKey: 'cases.blackbox.contradiction.instructions',
      sourceA: {
        titleKey: 'cases.blackbox.contradiction.sourceA',
        segments: [
          { id: 'note-isolated', textKey: 'cases.blackbox.contradiction.a1' },
          { id: 'note-signed', textKey: 'cases.blackbox.contradiction.a2' },
        ],
      },
      sourceB: {
        titleKey: 'cases.blackbox.contradiction.sourceB',
        segments: [
          { id: 'audit-shared', textKey: 'cases.blackbox.contradiction.b1' },
          { id: 'audit-unsigned', textKey: 'cases.blackbox.contradiction.b2' },
        ],
      },
      validPairs: [
        { aSegmentId: 'note-isolated', bSegmentId: 'audit-shared' },
        { aSegmentId: 'note-signed', bSegmentId: 'audit-unsigned' },
      ],
      unlockCondition: { type: 'puzzle_solved', puzzleId: 'blackbox-logs' },
      hints: [
        { id: 'bb-con-h1', level: 1, textKey: 'cases.blackbox.contradiction.hint1' },
        {
          id: 'bb-con-h2',
          level: 2,
          textKey: 'cases.blackbox.contradiction.hint2',
          highlightTargetId: 'note-isolated',
        },
        {
          id: 'bb-con-h3',
          level: 3,
          textKey: 'cases.blackbox.contradiction.hint3',
          highlightTargetId: 'audit-shared',
        },
      ],
    },
    {
      id: 'blackbox-connections',
      type: 'connection_board',
      titleKey: 'cases.blackbox.connections.title',
      instructionsKey: 'cases.blackbox.connections.instructions',
      nodeIds: [
        'build-release',
        'drone-test',
        'route-test',
        'station-test',
        'hotel-test',
        'operator-note',
      ],
      allowedConnectionTypes: ['supports', 'contradicts', 'causes'],
      requiredConnections: [
        { from: 'build-release', to: 'drone-test', type: 'causes' },
        { from: 'build-release', to: 'route-test', type: 'causes' },
        { from: 'build-release', to: 'station-test', type: 'causes' },
        { from: 'build-release', to: 'hotel-test', type: 'causes' },
        { from: 'operator-note', to: 'build-release', type: 'contradicts' },
      ],
      unlockCondition: { type: 'puzzle_solved', puzzleId: 'blackbox-contradiction' },
      hints: [
        { id: 'bb-link-h1', level: 1, textKey: 'cases.blackbox.connections.hint1' },
        {
          id: 'bb-link-h2',
          level: 2,
          textKey: 'cases.blackbox.connections.hint2',
          highlightTargetId: 'build-release',
        },
        {
          id: 'bb-link-h3',
          level: 3,
          textKey: 'cases.blackbox.connections.hint3',
          highlightTargetId: 'operator-note',
        },
      ],
    },
  ],
  hypotheses: [
    {
      id: 'coincidence',
      labelKey: 'cases.blackbox.hypothesis.coincidence',
      explanationKey: 'cases.blackbox.hypothesis.coincidence.explanation',
    },
    {
      id: 'shared-test-build',
      labelKey: 'cases.blackbox.hypothesis.shared',
      explanationKey: 'cases.blackbox.hypothesis.shared.explanation',
    },
    {
      id: 'remote-attacker',
      labelKey: 'cases.blackbox.hypothesis.attacker',
      explanationKey: 'cases.blackbox.hypothesis.attacker.explanation',
    },
  ],
  solution: {
    correctHypothesisId: 'shared-test-build',
    requiredEvidenceIds: [
      'build-release',
      'drone-test',
      'route-test',
      'station-test',
      'hotel-test',
    ],
    requiredPuzzleIds: [
      'blackbox-timeline',
      'blackbox-logs',
      'blackbox-contradiction',
      'blackbox-connections',
    ],
    explanationKey: 'cases.blackbox.solution',
  },
  scoring: { maxHintsForThreeStars: 1, maxHintsForTwoStars: 5 },
};
