import type { CaseDefinition } from '@/domain/case/caseSchema';

const always = { type: 'always' } as const;

export const nightRouteCase = {
  id: 'case-night-route',
  schemaVersion: 1,
  titleKey: 'cases.night.title',
  summaryKey: 'cases.night.summary',
  briefingKey: 'cases.night.briefing',
  difficulty: 'easy',
  estimatedMinutes: 8,
  evidence: [
    {
      id: 'route-plan',
      type: 'location_record',
      titleKey: 'cases.night.evidence.plan.title',
      descriptionKey: 'cases.night.evidence.plan.description',
      content: { kind: 'timeline_item', time: '23:40', bodyKey: 'cases.night.evidence.plan.body' },
      unlockCondition: always,
      tags: ['route', 'timeline'],
    },
    {
      id: 'gps-alert',
      type: 'sensor_record',
      titleKey: 'cases.night.evidence.gps.title',
      descriptionKey: 'cases.night.evidence.gps.description',
      content: { kind: 'timeline_item', time: '23:47', bodyKey: 'cases.night.evidence.gps.body' },
      unlockCondition: always,
      tags: ['gps', 'timeline'],
    },
    {
      id: 'access-audit',
      type: 'system_log',
      titleKey: 'cases.night.evidence.access.title',
      descriptionKey: 'cases.night.evidence.access.description',
      content: {
        kind: 'timeline_item',
        time: '23:48',
        bodyKey: 'cases.night.evidence.access.body',
      },
      unlockCondition: always,
      tags: ['access', 'timeline'],
    },
    {
      id: 'route-log',
      type: 'system_log',
      titleKey: 'cases.night.evidence.route.title',
      descriptionKey: 'cases.night.evidence.route.description',
      content: { kind: 'timeline_item', time: '23:55', bodyKey: 'cases.night.evidence.route.body' },
      unlockCondition: always,
      tags: ['route', 'timeline'],
    },
  ],
  puzzles: [
    {
      id: 'night-timeline',
      type: 'timeline',
      titleKey: 'cases.night.timeline.title',
      instructionsKey: 'cases.night.timeline.instructions',
      itemIds: ['route-log', 'gps-alert', 'route-plan', 'access-audit'],
      correctOrder: ['route-plan', 'gps-alert', 'access-audit', 'route-log'],
      unlockCondition: always,
      hints: [
        { id: 'night-time-h1', level: 1, textKey: 'cases.night.timeline.hint1' },
        {
          id: 'night-time-h2',
          level: 2,
          textKey: 'cases.night.timeline.hint2',
          highlightTargetId: 'access-audit',
        },
        {
          id: 'night-time-h3',
          level: 3,
          textKey: 'cases.night.timeline.hint3',
          highlightTargetId: 'route-log',
        },
      ],
    },
    {
      id: 'night-logs',
      type: 'log_analyzer',
      titleKey: 'cases.night.logs.title',
      instructionsKey: 'cases.night.logs.instructions',
      rows: [
        {
          id: 'log-1',
          time: '23:40',
          source: 'NAV',
          level: 'info',
          device: 'Cargo-04',
          messageKey: 'cases.night.logs.row1',
        },
        {
          id: 'log-2',
          time: '23:45',
          source: 'MOTOR',
          level: 'info',
          device: 'Cargo-04',
          messageKey: 'cases.night.logs.row2',
        },
        {
          id: 'log-3',
          time: '23:47',
          source: 'GPS',
          level: 'warning',
          device: 'Cargo-04',
          messageKey: 'cases.night.logs.row3',
        },
        {
          id: 'log-4',
          time: '23:48',
          source: 'ACCESS',
          level: 'warning',
          device: 'Console-2',
          messageKey: 'cases.night.logs.row4',
        },
        {
          id: 'log-5',
          time: '23:49',
          source: 'NAV',
          level: 'error',
          device: 'Cargo-04',
          messageKey: 'cases.night.logs.row5',
        },
        {
          id: 'log-6',
          time: '23:55',
          source: 'DOOR',
          level: 'info',
          device: 'Warehouse-7',
          messageKey: 'cases.night.logs.row6',
        },
      ],
      requiredRowIds: ['log-4', 'log-5'],
      allowedMistakes: 0,
      unlockCondition: { type: 'puzzle_solved', puzzleId: 'night-timeline' },
      hints: [
        { id: 'night-log-h1', level: 1, textKey: 'cases.night.logs.hint1' },
        {
          id: 'night-log-h2',
          level: 2,
          textKey: 'cases.night.logs.hint2',
          highlightTargetId: 'log-4',
        },
        {
          id: 'night-log-h3',
          level: 3,
          textKey: 'cases.night.logs.hint3',
          highlightTargetId: 'log-5',
        },
      ],
    },
  ],
  hypotheses: [
    {
      id: 'software-fault',
      labelKey: 'cases.night.hypothesis.software',
      explanationKey: 'cases.night.hypothesis.software.explanation',
    },
    {
      id: 'gps-spoofing',
      labelKey: 'cases.night.hypothesis.gps',
      explanationKey: 'cases.night.hypothesis.gps.explanation',
    },
    {
      id: 'authorized-intervention',
      labelKey: 'cases.night.hypothesis.access',
      explanationKey: 'cases.night.hypothesis.access.explanation',
    },
  ],
  solution: {
    correctHypothesisId: 'authorized-intervention',
    requiredEvidenceIds: ['access-audit', 'route-log'],
    requiredPuzzleIds: ['night-timeline', 'night-logs'],
    explanationKey: 'cases.night.solution',
  },
  scoring: { maxHintsForThreeStars: 1, maxHintsForTwoStars: 3 },
} satisfies CaseDefinition;
