import type { CaseDefinition } from '@/domain/case/caseSchema';

const always = { type: 'always' } as const;

export const silentStationCase: CaseDefinition = {
  id: 'case-silent-station',
  schemaVersion: 1,
  titleKey: 'cases.station.title',
  summaryKey: 'cases.station.summary',
  briefingKey: 'cases.station.briefing',
  difficulty: 'medium',
  estimatedMinutes: 12,
  evidence: [
    {
      id: 'sensor-heartbeat',
      type: 'sensor_record',
      titleKey: 'cases.station.evidence.sensor.title',
      descriptionKey: 'cases.station.evidence.sensor.description',
      content: { kind: 'text', bodyKey: 'cases.station.evidence.sensor.body' },
      unlockCondition: always,
      tags: ['sensor'],
    },
    {
      id: 'camera-loop',
      type: 'image',
      titleKey: 'cases.station.evidence.camera.title',
      descriptionKey: 'cases.station.evidence.camera.description',
      content: { kind: 'text', bodyKey: 'cases.station.evidence.camera.body' },
      unlockCondition: always,
      tags: ['camera'],
    },
    {
      id: 'platform-report',
      type: 'statement',
      titleKey: 'cases.station.evidence.report.title',
      descriptionKey: 'cases.station.evidence.report.description',
      content: { kind: 'text', bodyKey: 'cases.station.evidence.report.body' },
      unlockCondition: always,
      tags: ['statement'],
    },
    {
      id: 'relay-access',
      type: 'system_log',
      titleKey: 'cases.station.evidence.relay.title',
      descriptionKey: 'cases.station.evidence.relay.description',
      content: { kind: 'text', bodyKey: 'cases.station.evidence.relay.body' },
      unlockCondition: { type: 'puzzle_solved', puzzleId: 'station-logs' },
      tags: ['access'],
    },
    {
      id: 'test-signature',
      type: 'system_log',
      titleKey: 'cases.station.evidence.signature.title',
      descriptionKey: 'cases.station.evidence.signature.description',
      content: { kind: 'text', bodyKey: 'cases.station.evidence.signature.body' },
      unlockCondition: { type: 'puzzle_solved', puzzleId: 'station-contradiction' },
      tags: ['software'],
    },
  ],
  puzzles: [
    {
      id: 'station-logs',
      type: 'log_analyzer',
      titleKey: 'cases.station.logs.title',
      instructionsKey: 'cases.station.logs.instructions',
      rows: [
        {
          id: 'st-l1',
          time: '18:11',
          source: 'SENSOR',
          level: 'info',
          device: 'P-4',
          messageKey: 'cases.station.logs.row1',
        },
        {
          id: 'st-l2',
          time: '18:12',
          source: 'CAM',
          level: 'info',
          device: 'C-12',
          messageKey: 'cases.station.logs.row2',
        },
        {
          id: 'st-l3',
          time: '18:14',
          source: 'RELAY',
          level: 'warning',
          device: 'R-2',
          messageKey: 'cases.station.logs.row3',
        },
        {
          id: 'st-l4',
          time: '18:14',
          source: 'SENSOR',
          level: 'error',
          device: 'P-4',
          messageKey: 'cases.station.logs.row4',
        },
        {
          id: 'st-l5',
          time: '18:15',
          source: 'CAM',
          level: 'warning',
          device: 'C-12',
          messageKey: 'cases.station.logs.row5',
        },
        {
          id: 'st-l6',
          time: '18:17',
          source: 'TRAIN',
          level: 'info',
          device: 'T-8',
          messageKey: 'cases.station.logs.row6',
        },
      ],
      requiredRowIds: ['st-l3', 'st-l5'],
      allowedMistakes: 0,
      unlockCondition: always,
      hints: [
        { id: 'st-log-h1', level: 1, textKey: 'cases.station.logs.hint1' },
        {
          id: 'st-log-h2',
          level: 2,
          textKey: 'cases.station.logs.hint2',
          highlightTargetId: 'st-l3',
        },
        {
          id: 'st-log-h3',
          level: 3,
          textKey: 'cases.station.logs.hint3',
          highlightTargetId: 'st-l5',
        },
      ],
    },
    {
      id: 'station-contradiction',
      type: 'contradiction',
      titleKey: 'cases.station.contradiction.title',
      instructionsKey: 'cases.station.contradiction.instructions',
      sourceA: {
        titleKey: 'cases.station.contradiction.sourceA',
        segments: [
          { id: 'report-clear', textKey: 'cases.station.contradiction.a1' },
          { id: 'report-time', textKey: 'cases.station.contradiction.a2' },
        ],
      },
      sourceB: {
        titleKey: 'cases.station.contradiction.sourceB',
        segments: [
          { id: 'frame-motion', textKey: 'cases.station.contradiction.b1' },
          { id: 'frame-repeat', textKey: 'cases.station.contradiction.b2' },
        ],
      },
      validPairs: [{ aSegmentId: 'report-clear', bSegmentId: 'frame-repeat' }],
      unlockCondition: always,
      hints: [
        { id: 'st-con-h1', level: 1, textKey: 'cases.station.contradiction.hint1' },
        {
          id: 'st-con-h2',
          level: 2,
          textKey: 'cases.station.contradiction.hint2',
          highlightTargetId: 'report-clear',
        },
        {
          id: 'st-con-h3',
          level: 3,
          textKey: 'cases.station.contradiction.hint3',
          highlightTargetId: 'frame-repeat',
        },
      ],
    },
    {
      id: 'station-connections',
      type: 'connection_board',
      titleKey: 'cases.station.connections.title',
      instructionsKey: 'cases.station.connections.instructions',
      nodeIds: ['sensor-heartbeat', 'camera-loop', 'relay-access', 'test-signature'],
      allowedConnectionTypes: ['supports', 'causes'],
      requiredConnections: [
        { from: 'relay-access', to: 'sensor-heartbeat', type: 'causes' },
        { from: 'test-signature', to: 'camera-loop', type: 'supports' },
      ],
      unlockCondition: {
        type: 'all',
        conditions: [
          { type: 'puzzle_solved', puzzleId: 'station-logs' },
          { type: 'puzzle_solved', puzzleId: 'station-contradiction' },
        ],
      },
      hints: [
        { id: 'st-link-h1', level: 1, textKey: 'cases.station.connections.hint1' },
        {
          id: 'st-link-h2',
          level: 2,
          textKey: 'cases.station.connections.hint2',
          highlightTargetId: 'relay-access',
        },
        {
          id: 'st-link-h3',
          level: 3,
          textKey: 'cases.station.connections.hint3',
          highlightTargetId: 'test-signature',
        },
      ],
    },
  ],
  hypotheses: [
    {
      id: 'power-failure',
      labelKey: 'cases.station.hypothesis.power',
      explanationKey: 'cases.station.hypothesis.power.explanation',
    },
    {
      id: 'network-outage',
      labelKey: 'cases.station.hypothesis.network',
      explanationKey: 'cases.station.hypothesis.network.explanation',
    },
    {
      id: 'test-replay',
      labelKey: 'cases.station.hypothesis.replay',
      explanationKey: 'cases.station.hypothesis.replay.explanation',
    },
  ],
  solution: {
    correctHypothesisId: 'test-replay',
    requiredEvidenceIds: ['relay-access', 'test-signature', 'camera-loop'],
    requiredPuzzleIds: ['station-logs', 'station-contradiction', 'station-connections'],
    explanationKey: 'cases.station.solution',
  },
  scoring: { maxHintsForThreeStars: 1, maxHintsForTwoStars: 4 },
};
